source:
  # GIT https url of your helm files
  repoURL: 'https://github.com/Gi1Ga/devops-helm.git'
  # Git branch name of your helm package
  targetRevision: main
  path: qua/myapp
  helm:
    releaseName: myapp
    valueFile: values.yaml
destination:
  namespace: qua
  name: docker-desktop